channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=2
- nodejs=11
- nbconvert=5.5
- widgetsnbextension=3.5
# Python Kernel
- matplotlib=3.3
- pandas=0.24
- python=3.7
- sympy=1.4
- numpy=1.19
- scipy=1.5